### PR TITLE
Notification

### PR DESCRIPTION
**Pull request by ykurata**
I created dropdown notifications on the navbar.
This is the first time using Material UI for me, if there is something wrong, please let me know. Thanks!

### CODE REVIEW

**Review by Kartihan-sri — COMMENTED** [review]
Notification looks really clean! Only comment I can think of is you might want to split up the notifications using cards, and possibly use a list (which uses divider to separate each notification, and in case of a lot of notifications user can scroll).

**Comment by ykurata** [comment]
> Notification looks really clean! Only comment I can think of is you might want to split up the notifications using cards, and possibly use a list (which uses divider to separate each notification, and in case of a lot of notifications user can scroll).

Ok, I split up the notifications by cards, and used a list. So, if there are more than 3 notifications, there will be a scroll bar.

**Comment by Kartihan-sri** [comment]
> > Notification looks really clean! Only comment I can think of is you might want to split up the notifications using cards, and possibly use a list (which uses divider to separate each notification, and in case of a lot of notifications user can scroll).
> 
> Ok, I split up the notifications by cards, and used a list. So, if there are more than 3 notifications, there will be a scroll bar.

Awesome! Just a comment, when clicking on the notifications It still seems like that whole list is clickable and not the individual notification but that's fine for now. It's perfect for what we need!

**Review by Kartihan-sri — APPROVED** [review]

**Comment by ykurata** [comment]
> > > Notification looks really clean! Only comment I can think of is you might want to split up the notifications using cards, and possibly use a list (which uses divider to separate each notification, and in case of a lot of notifications user can scroll).
> > 
> > 
> > Ok, I split up the notifications by cards, and used a list. So, if there are more than 3 notifications, there will be a scroll bar.
> 
> Awesome! Just a comment, when clicking on the notifications It still seems like that whole list is clickable and not the individual notification but that's fine for now. It's perfect for what we need!

That's a good point! I'll fix it

**Pull request merged**
